### PR TITLE
More prose, extra explanations, tone changes

### PR DESCRIPTION
**Pull request by hugbubby**
Added some new explanations when necessary and rewrote some portions to avoid repeating earlier sections and using roundabout language. Also fixed some typos. Lot changes here so if you have any disputes just be sure to ask and I'll make another commit.

### CODE REVIEW

**Comment by serhack** [comment]
@hugbubby Hello, could you please review #17 instead of this pull request? #17 was written by a professional proofreader.

**Comment by hugbubby** [comment]
I'm sorry, I didn't realize someone had already edited the document and was waiting on a reviewer. My apologies.

**Comment by serhack** [comment]
Don't worry, I'm going to put some "tags" in order to clarify pull requests :)

**Comment by UncagedPotential** [comment]
Hi @hugbubby, I just read through your notes - great edits, I like your style. :- )

I'm editing/proofreading Mastering Monero, and your writing includes some snippets and phrasings that I would love to include in this resource. If you don't mind, I might sprinkle a few of your contributions throughout the book?

Cheers,
-:- Mitchell

**Comment by hugbubby** [comment]
Awwwwwww! I'd be flattered.

**Pull request closed without merging**
