### PR TITLE
Create esp

### PR DESCRIPTION
**Pull request by orientaru**
Space to stack up the spanish translation of the book.

### CODE REVIEW

**Comment by serhack** [comment]
The file name is for few people 😂

**Comment by orientaru** [comment]
Putting aside my stupidity :p. Do we use ISO 639-1 codes or ISO 639-2?

To have a reminder to not do this stuff again :^)

**Comment by serhack** [comment]
ISO 639-1

**Comment by orientaru** [comment]
Got it

**Pull request closed without merging**
